import Foundation

let descriptionText = "Sed varius congue mi quis maximus. Vivamus eleifend felis rutrum, placerat mauris interdum, molestie ligula. Mauris pellentesque elit eu ante eleifend sollicitudin. Nullam at lacus nec risus luctus interdum ut sit amet odio. Fusce varius cursus orci a tempor. Cras imperdiet, mi in rhoncus pharetra, purus nisl tempus tellus, quis egestas nibh nisl eget massa. Cras varius mauris vitae rutrum blandit. Integer dapibus nisi ac metus iaculis maximus. Sed eget rhoncus justo, et dictum erat. Suspendisse sed tincidunt dolor. Nullam et turpis a turpis fermentum congue vel ut enim. Ut risus ipsum, finibus nec dui ultrices, congue dictum mi. Mauris ut malesuada sem, non bibendum odio. Nulla facilisi. Maecenas velit urna, ornare consequat egestas eu, venenatis at sem. Quisque faucibus lectus id sem congue tincidunt. Aliquam rutrum justo vitae est convallis accumsan. Suspendisse ante ante, tempus vitae laoreet et, facilisis vitae arcu. Aenean malesuada ex turpis, a tincidunt elit consequat ac. Cras eu dolor a ligula volutpat feugiat. Nunc accumsan libero id lectus lobortis ullamcorper. Duis purus eros, tristique dignissim maximus et, commodo quis sem. Nulla luctus, tellus id mattis bibendum, magna diam posuere nisi, elementum viverra massa tellus sit amet erat. Suspendisse potenti. Integer et tortor enim. Nam vel lacus porta, consectetur orci ac, faucibus purus. Praesent sit amet elit pulvinar neque volutpat malesuada. Donec malesuada sagittis est, id tempus eros volutpat in. Integer quis lacus eget mi feugiat dignissim sit amet sit amet eros. Duis sollicitudin risus sem, eu efficitur metus interdum sed. Duis aliquet id eros sit amet tempor."

let data = [
    ListItem(id: UUID(), name: "Soba Noodles", description: descriptionText, country: "Chine", imgUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2020/12/Noodles-with-chilli-oil-eggs-6ec34e9.jpg", price: 10.0),
    ListItem(id: UUID(), name: "Soba Noodles",  description: descriptionText, country: "Chine", imgUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2020/12/Noodles-with-chilli-oil-eggs-6ec34e9.jpg", price: 10.0),
    ListItem(id: UUID(), name: "Soba Noodles",  description: descriptionText, country: "Chine", imgUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2020/12/Noodles-with-chilli-oil-eggs-6ec34e9.jpg", price: 10.0),
    ListItem(id: UUID(), name: "Soba Noodles",  description: descriptionText, country: "Chine", imgUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2020/12/Noodles-with-chilli-oil-eggs-6ec34e9.jpg", price: 10.0),
    ListItem(id: UUID(), name: "Soba Noodles",  description: descriptionText, country: "Chine", imgUrl: "https://images.immediate.co.uk/production/volatile/sites/30/2020/12/Noodles-with-chilli-oil-eggs-6ec34e9.jpg", price: 10.0)
]
